import React, { useState } from 'react';
import {
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Bell,
  Check,
  CheckCheck,
  CheckCircle2,
  Clock,
  Cpu,
  Filter,
  Info,
  Radio,
  ShieldAlert,
  Trash2,
} from 'lucide-react';
import { useFarm } from '../../context/FarmContext';
import { FarmAlert } from '../../types';

export const AlertCenterView: React.FC = () => {
  const { alerts, markAlertAsRead, clearAlerts, unreadAlertsCount } = useFarm();
  const [severityFilter, setSeverityFilter] = useState<'ALL' | 'CRITICAL' | 'WARNING' | 'INFO'>('ALL');

  const filteredAlerts = alerts.filter((alert) => {
    if (severityFilter === 'ALL') return true;
    return alert.severity === severityFilter;
  });

  const getSeverityBadge = (severity: 'CRITICAL' | 'WARNING' | 'INFO') => {
    switch (severity) {
      case 'CRITICAL':
        return 'bg-rose-950/80 text-rose-300 border-rose-600/70 font-extrabold';
      case 'WARNING':
        return 'bg-amber-950/80 text-amber-300 border-amber-600/70 font-bold';
      case 'INFO':
      default:
        return 'bg-cyan-950/80 text-cyan-300 border-cyan-600/70 font-semibold';
    }
  };

  const getSourceIcon = (source: string) => {
    switch (source) {
      case 'Edge AI':
        return Cpu;
      case 'Environmental Model':
        return ShieldAlert;
      case 'Sensor':
      default:
        return Radio;
    }
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Top Banner */}
      <div className="bg-[#081e16] border border-emerald-900/80 rounded-2xl p-5 sm:p-6 shadow-md">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <span className="text-xs font-mono font-bold text-rose-400 uppercase tracking-widest">
                Event Dispatch Engine
              </span>
              <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-emerald-950 text-emerald-300 border border-emerald-800/40">
                {unreadAlertsCount} Unread Events
              </span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-white font-heading">
              Field Alert Center
            </h1>
            <p className="text-xs sm:text-sm text-slate-300 mt-1">
              Real-time automated incident logs generated by edge sensors, foliar vision, and environmental models
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2.5">
            {/* Severity Filter buttons */}
            <div className="flex items-center p-1 rounded-xl bg-[#05130e] border border-emerald-900/60 text-xs">
              {(['ALL', 'CRITICAL', 'WARNING', 'INFO'] as const).map((sev) => (
                <button
                  key={sev}
                  onClick={() => setSeverityFilter(sev)}
                  className={`px-3 py-1.5 rounded-lg font-bold transition cursor-pointer ${
                    severityFilter === sev
                      ? 'bg-emerald-600 text-white shadow'
                      : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {sev}
                </button>
              ))}
            </div>

            {/* Clear button */}
            <button
              onClick={clearAlerts}
              className="p-2.5 rounded-xl bg-emerald-950/60 hover:bg-emerald-900/60 text-slate-400 hover:text-rose-300 border border-emerald-900 text-xs font-semibold transition cursor-pointer"
              title="Clear all alerts"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      {/* Alerts List */}
      <div className="space-y-3">
        {filteredAlerts.length === 0 ? (
          <div className="p-12 text-center rounded-2xl bg-[#081b14] border border-emerald-950/80 space-y-2">
            <CheckCircle2 className="w-10 h-10 text-emerald-400 mx-auto" />
            <h3 className="text-base font-bold text-white font-heading">
              No Active Alerts in this Category
            </h3>
            <p className="text-xs text-slate-400 max-w-sm mx-auto">
              All field sensors and microclimate parameters are operating within established safe thresholds.
            </p>
          </div>
        ) : (
          filteredAlerts.map((alert: FarmAlert) => {
            const SourceIcon = getSourceIcon(alert.source);
            return (
              <div
                key={alert.id}
                className={`p-5 rounded-2xl border transition-all flex flex-col md:flex-row md:items-center justify-between gap-4 ${
                  alert.isRead
                    ? 'bg-[#071912]/70 border-emerald-950/80 text-slate-300'
                    : 'bg-[#081e16] border-emerald-700/60 text-white shadow-sm'
                }`}
              >
                <div className="flex items-start gap-4">
                  {/* Severity icon box */}
                  <div
                    className={`p-3 rounded-xl border shrink-0 mt-0.5 ${
                      alert.severity === 'CRITICAL'
                        ? 'bg-rose-950/70 border-rose-700/70 text-rose-400'
                        : alert.severity === 'WARNING'
                        ? 'bg-amber-950/70 border-amber-700/70 text-amber-400'
                        : 'bg-cyan-950/70 border-cyan-700/70 text-cyan-400'
                    }`}
                  >
                    {alert.severity === 'CRITICAL' ? (
                      <AlertOctagon className="w-5 h-5" />
                    ) : alert.severity === 'WARNING' ? (
                      <AlertTriangle className="w-5 h-5" />
                    ) : (
                      <Info className="w-5 h-5" />
                    )}
                  </div>

                  {/* Body details */}
                  <div className="space-y-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className={`text-[10px] px-2 py-0.5 rounded-full border uppercase tracking-wider ${getSeverityBadge(alert.severity)}`}>
                        {alert.severity}
                      </span>
                      <span className="text-xs text-slate-400 flex items-center gap-1 font-mono">
                        <SourceIcon className="w-3.5 h-3.5 text-emerald-400" />
                        <span>Source: <strong className="text-slate-200">{alert.source}</strong></span>
                      </span>
                      <span className="text-slate-500 text-xs">·</span>
                      <span className="text-xs text-slate-400 flex items-center gap-1">
                        <Clock className="w-3 h-3" />
                        <span>{alert.timestamp}</span>
                      </span>
                    </div>

                    <h2 className="text-base font-bold text-white font-heading">
                      {alert.title}
                    </h2>
                    <p className="text-xs text-slate-300 leading-relaxed max-w-2xl">
                      {alert.message}
                    </p>

                    {/* Action Taken / Recommended */}
                    <div className="pt-2 flex items-start gap-2 text-xs text-emerald-300 bg-[#04100c] px-3 py-1.5 rounded-lg border border-emerald-950 w-fit">
                      <strong className="text-emerald-400">Action Recommended:</strong>
                      <span>{alert.actionRecommended}</span>
                    </div>
                  </div>
                </div>

                {/* Mark as read button */}
                <div className="flex items-center gap-2 shrink-0 self-end md:self-center">
                  {!alert.isRead ? (
                    <button
                      onClick={() => markAlertAsRead(alert.id)}
                      className="px-3 py-1.5 rounded-xl bg-emerald-950 hover:bg-emerald-900 border border-emerald-800 text-emerald-300 text-xs font-bold transition flex items-center gap-1 cursor-pointer"
                    >
                      <Check className="w-3.5 h-3.5" />
                      <span>Acknowledge</span>
                    </button>
                  ) : (
                    <span className="text-xs text-slate-400 flex items-center gap-1">
                      <CheckCheck className="w-4 h-4 text-emerald-500" />
                      <span>Acknowledged</span>
                    </span>
                  )}
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
